dist: trusty
sudo: required

language: node_js
node_js:
  - "stable"
addons:
  sonarcloud:
    organization: "likithjoel-github"
    token:
      secure: "967f5340e90e957d889d104b0c2c4e1b4df6ec4a"
script:
  - sonar-scanner
  - npm test